In [1]:
import pandas as pd
import json
import glob
import yaml
from datetime import datetime
from urllib.parse import urlparse
import pyarrow

In [2]:
with open("../history/summary.json") as f:
    data = json.load(f)

dfs = []
for item in data:
    temp_df = pd.DataFrame(
        item["dailyMinutesDown"].items(), columns=["date", "time"]
    )
    temp_df["domain"] = urlparse(item["url"]).netloc
    temp_df["type"] = "down"
    dfs.append(temp_df)

df = pd.concat(dfs, ignore_index=True)

In [3]:
# Buscar todos los archivos YAML en la carpeta "history"
yaml_files = glob.glob("../history/*.yml")
records = []

for file in yaml_files:
    with open(file) as f:
        data = yaml.safe_load(f)
    # Extraer el dominio a partir de la URL
    domain = urlparse(data.get("url", "")).netloc
    # Obtener y procesar el startTime para definir cuándo se creó el dominio
    start_time = data.get("startTime")
    creation_date = None
    if start_time:
        try:
            if isinstance(start_time, str):
                dt = datetime.fromisoformat(start_time.replace("Z", "+00:00"))
            else:
                dt = start_time
            creation_date = dt.date().isoformat()
        except Exception as e:
            print(f"Error al procesar startTime en {file}: {e}")
    last_update = data.get("lastUpdated")
    if last_update:
        try:
            if isinstance(last_update, str):
                dt = datetime.fromisoformat(last_update.replace("Z", "+00:00"))
            else:
                dt = last_update
            last_update = dt.date().isoformat()
        except Exception as e:
            print(f"Error al procesar lastUpdated en {file}: {e}")

    records.append(
        {"domain": domain, "date": creation_date, "time": 0, "type": "created"}
    )
    records.append(
        {"domain": domain, "date": last_update, "time": 0, "type": "last_updated"}
    )

# Crear un registro con la información de creación de cada dominio
df_domain_created = pd.DataFrame(records)
df = pd.concat([df, df_domain_created], ignore_index=True)
df

            date  time           domain  type
0     2026-04-04  1321   www.anh.gob.bo  down
1     2026-04-03  1440   www.anh.gob.bo  down
2     2026-04-02  1440   www.anh.gob.bo  down
3     2026-04-01  1440   www.anh.gob.bo  down
4     2026-03-31  1440   www.anh.gob.bo  down
...          ...   ...              ...   ...
1655  2025-07-06    56  www.rree.gob.bo  down
1656  2025-06-12    21  www.rree.gob.bo  down
1657  2026-04-04  1324       geo.gob.bo  down
1658  2026-04-03  1440       geo.gob.bo  down
1659  2026-04-02    27       geo.gob.bo  down

[1660 rows x 4 columns]

In [4]:
df["date"] = pd.to_datetime(df["date"]).dt.date
df["time"] = df["time"].astype(int)
df["domain"] = df["domain"].astype(str)
df["type"] = df["type"].astype("category")
df

            date  time           domain  type
0     2026-04-04  1321   www.anh.gob.bo  down
1     2026-04-03  1440   www.anh.gob.bo  down
2     2026-04-02  1440   www.anh.gob.bo  down
3     2026-04-01  1440   www.anh.gob.bo  down
4     2026-03-31  1440   www.anh.gob.bo  down
...          ...   ...              ...   ...
1655  2025-07-06    56  www.rree.gob.bo  down
1656  2025-06-12    21  www.rree.gob.bo  down
1657  2026-04-04  1324       geo.gob.bo  down
1658  2026-04-03  1440       geo.gob.bo  down
1659  2026-04-02    27       geo.gob.bo  down

[1660 rows x 4 columns]

In [5]:
df.to_parquet(
    "../data/summary.parquet",
    index=False,
    engine="pyarrow",
)

In [7]:
data_dir = "../data"

In [10]:
import subprocess
import re

with open(f"{data_dir}/dataset-metadata.json") as file:
    metadata = file.read()
    metadata = re.sub(r",\s*([}\]])", r"\1", metadata)
    kaggle_id = json.loads(metadata)["id"]

check = subprocess.run(
    ["kaggle", "datasets", "files", kaggle_id],
    capture_output=True,
    text=True,
)

if check.returncode == 0:
    subprocess.run(
        [
            "kaggle",
            "datasets",
            "version",
            "-p",
            data_dir,
            "-m",
            "daily update",
            "-t",
            "--delete-old-versions",
        ],
        check=True,
    )
else:
    # Ejemplo: 403 Forbidden -> crear dataset
    subprocess.run(
        ["kaggle", "datasets", "create", "-p", data_dir],
        check=True,
    )

You must authenticate before you can call the Kaggle API.
Follow the instructions to authenticate at: https://github.com/Kaggle/kaggle-cli/blob/main/docs/README.md#authentication

CalledProcessError: Command '['kaggle', 'datasets', 'create', '-p', '../data']' returned non-zero exit status 1.

In [ ]:
print("Cargado")